### ISSUE TITLE
Game doesn't start with AMDGPU/RADV (D9VK)

### ISSUE THREAD

**Issue by rafifos** [mmtrt/Wine-AppImage_old#1] opened 2019-06-26 20:58 UTC
I'm using Lutris (AppImage w/ d9vk) to run League. But it doesn't start the game.

I was able to pinpoint the issue:
```
C:/Riot Games/League of Legends/Game/League of Legends.exe: symbol lookup error: /usr/lib/i386-linux-gnu/libvulkan_radeon.so: undefined symbol: amdgpu_bo_list_create_raw
```

System info:
Intel Core i3 2100
Radeon R7 360 w/ amdgpu/radv

**Comment by mmtrt** [comment] 2019-06-29 07:02
Sorry about not replying, as I was not watching the repo for some reason it did not set it auto could be because it's empty.

So about the issue appimage does not have that library nor vk pkgs could be the reason.

`libvulkan_radeon.so`

**Comment by mmtrt** [comment] 2019-06-30 06:02
can you try lol patched appimage from https://github.com/mmtrt/Wine_Appimage/releases/tag/continuous see if this fixes the issue.

**Comment by rafifos** [comment] 2019-06-30 18:26
Juts tried with a clean prefix, same behaviour and same output.

**Comment by rafifos** [comment] 2019-06-30 18:27
Is there any way to LD_PRELOAD outside of the AppImage? This might fix the issue, since the host probably have the Vulkan drivers installed.

**Comment by mmtrt** [comment] 2019-06-30 18:38
I think the issue is with vk icd file which points to vulkan driver library, lutris have this options select different icd files can you check which one is selected make sure it is set to `radeon i686` something like that.

**Comment by rafifos** [comment] 2019-06-30 18:54
Yeah, i've selected `radeon_i686.json`.

Without it, the client doesn't even start.

**Comment by mmtrt** [comment] 2019-06-30 19:44
so game is working now?

Did you tried preloading that libvulkan radeon file  with starting of appimage command.

**Comment by rafifos** [comment] 2019-07-01 19:05
No, it didn't work.

I cannot preload the library since my system is amd64 and the lib is i386. It gives me an wrong ELFCLASS error.

**Comment by mmtrt** [comment] 2019-07-02 14:30
Can try lol patched appimage from continuous release as today also make sure disable lutris vk icd file as now appimage will load it from itself now.  See if that fixes your issue.

**Comment by rafifos** [comment] 2019-07-03 00:51
`archlinux` (**SHA256**: `bc804ca1bc6ff08f03f4d1cc86c8bb855d29387617e99e2242c6d54689eff889`) is working, I will test it more thought.

Same issue with the lastest `bionic` (**SHA256**: `de641ad7d1d01ed2e91b1c74bbb0292cc45b90b56b404e22c7d11408e4ed7476`)

This is the log when trying to enter a match (on `bionic`):
```
0212:err:thread:sigsys_handler SIGSYS (173)
0213:err:thread:sigsys_handler SIGSYS (173)
0215:err:thread:sigsys_handler SIGSYS (173)
0214:err:thread:sigsys_handler SIGSYS (173)
0216:err:thread:sigsys_handler SIGSYS (173)
0217:err:thread:sigsys_handler SIGSYS (173)
0218:err:thread:sigsys_handler SIGSYS (173)
021a:err:thread:sigsys_handler SIGSYS (173)
021c:err:thread:sigsys_handler SIGSYS (173)
021d:err:thread:sigsys_handler SIGSYS (173)
021e:err:thread:sigsys_handler SIGSYS (173)
021f:err:thread:sigsys_handler SIGSYS (173)
0220:err:thread:sigsys_handler SIGSYS (173)
0224:err:thread:sigsys_handler SIGSYS (173)
0225:err:thread:sigsys_handler SIGSYS (173)
0226:err:thread:sigsys_handler SIGSYS (173)
0227:err:thread:sigsys_handler SIGSYS (173)
0228:err:thread:sigsys_handler SIGSYS (173)
0229:err:thread:sigsys_handler SIGSYS (173)
022a:err:thread:sigsys_handler SIGSYS (173)
WARNING: radv is not a conformant vulkan implementation, testing use only.
WARNING: radv is not a conformant vulkan implementation, testing use only.
022b:err:thread:sigsys_handler SIGSYS (173)
022c:err:thread:sigsys_handler SIGSYS (173)
022d:err:thread:sigsys_handler SIGSYS (173)
022f:err:thread:sigsys_handler SIGSYS (173)
022e:err:thread:sigsys_handler SIGSYS (173)
C:/Riot Games/League of Legends/Game/League of Legends.exe: symbol lookup error: /usr/lib/i386-linux-gnu/libvulkan_radeon.so: undefined symbol: amdgpu_bo_list_create_raw
```

**Comment by mmtrt** [comment] 2019-07-03 04:10
~~That issue could be due to old drivers on `bionic` appimage compare to `archlinux`.~~

EDIT: This issue on `bionic` appimage should be fixed now. As vk icd files on appimage earlier build had path pointing to `/usr/lib/i386-linux-gnu`

**Closed as completed** 2019-07-04 08:33 UTC
